version: '3.9'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: tabs-manager
      POSTGRES_PASSWORD: localPassword
      POSTGRES_DB: tabs-manager
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data